In [33]:
import pandas as pd 

list = {
    "test":[1, 2, "well"],
    "test2":[2, "eli", 1]
    }
list_pd = pd.DataFrame(list)

# list_pd.loc[]
list_pd

   test test2
0     1     2
1     2   eli
2  well     1

In [46]:
test_df = list_pd.iloc[2:1]


# test_df = list_pd.loc[:,"test"]
test_df

Empty DataFrame
Columns: [test, test2]
Index: []