In [3]:
import pandas as pd, sqlalchemy as sqla, numpy as np
import decouple
from sqlalchemy import String, Integer
from IPython.display import display

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option('display.max_colwidth', 1000)

mis_file_path = decouple.config("MIS_FILE_PATH")

mis_db = sqla.create_engine(decouple.config("MIS_DB"))
red_db = sqla.create_engine(decouple.config("RED_DB"))

print(mis_db)
print(red_db)

Engine(mysql+mysqlconnector://mis-admin:***@cloneserver:3306)
Engine(mysql+mysqlconnector://mis-zedrick:***@120.28.99.16:3306)

In [4]:
# truncate existing
with red_db.connect() as conn:
    conn.execute(sqla.text("TRUNCATE TABLE redreport2026.overall_schedules;"))
    conn.execute(sqla.text("TRUNCATE TABLE redreport2026.overall_account_categories;"))
    conn.execute(sqla.text("TRUNCATE TABLE redreport2026.overall_universe_accounts;"))

In [5]:
# Schedule

# Get dimensions
store_details = pd.read_sql_table(table_name="store_details", con=mis_db, schema="ref")

# Get approved schedules
red_sched = pd.read_excel(f"{mis_file_path}MIS Data\\RED Alert\\RED Bulk Upload.xlsx", sheet_name="Approved Schedule")
red_sched = red_sched[["Day", "Employee Code", "Account Name", "Store Code"]]
red_sched = red_sched.drop_duplicates()

red_sched = pd.merge(
    red_sched, 
    store_details[["account_name", "store_code", "bpc_store_code"]],
    left_on=["Account Name", "Store Code"],
    right_on=["account_name", "store_code"],
    how="left"
)

red_sched["schedule_id"] = range(1, len(red_sched) + 1, 1)
red_sched = red_sched[["schedule_id", "Day", "Employee Code", "bpc_store_code"]]

red_sched = red_sched.rename(columns={
    "Day": "day_of_the_week",
    "Employee Code": "emp_code"
})

# Load to database
red_sched.to_sql(name="overall_schedules", con=red_db, schema="redreport2026", if_exists="append", index=False, dtype={
    "schedule_id": Integer,
    "day_of_the_week": String(255),
    "emp_code": String(500),
    "bpc_store_code": String(1000)
})

display(red_sched.shape)
display(red_sched.head(5))
display(red_sched.tail(5))

(7083, 4)

   schedule_id day_of_the_week     emp_code bpc_store_code
0            1          Monday  RIII-MPA-01  BPC-MDC-00409
1            2          Friday  RIII-MPA-01  BPC-MDC-00409
2            3          Monday  RIII-MPA-01  BPC-WPC-00146
3            4          Friday  RIII-MPA-01  BPC-WPC-00146
4            5          Monday  RIII-MPA-01  BPC-RSC-00059

      schedule_id day_of_the_week    emp_code bpc_store_code
7078         7079       Wednesday  NCR-MDE-02  BPC-MDC-00073
7079         7080          Friday  NCR-MDE-02  BPC-MDC-00786
7080         7081          Monday  NCR-MDE-02  BPC-MDC-00902
7081         7082        Saturday  NCR-MDE-02  BPC-MDC-00807
7082         7083        Thursday  NCR-MDE-02  BPC-MDC-00383

In [6]:
# Promos

store_details = pd.read_sql_table(table_name="store_details", con=mis_db, schema="ref")
store_details["account_code"] = store_details["bpc_store_code"].str.extract(r"BPC-(\D+)-\d+")
store_details["promo_name"] = "N/A"
store_details = store_details[["account_code", "account_name", "promo_name"]]
store_details = store_details.drop_duplicates()

promos = pd.read_excel(f"{mis_file_path}MIS Data\\RED Alert\\RED Bulk Upload.xlsx", sheet_name="Promos")

# Append N/A and promos
red_promos = pd.concat([promos, store_details], ignore_index=True)

red_promos = red_promos.sort_values(["account_name", "promo_name"])
red_promos["id"] = range(1, len(red_promos) + 1, 1)

red_promos = red_promos[["id", "account_code", "account_name", "promo_name"]]
red_promos = red_promos.reset_index(drop=True)

# Load to database
red_promos.to_sql(name="overall_account_categories", con=red_db, schema="redreport2026", if_exists="append", index=False, dtype={
    "id": Integer,
    "account_code":	String(255),		
    # "account_name":	String(),		
    "promo_name":	String(10000)
})

display(red_promos.shape)
display(red_promos.head(5))
display(red_promos.tail(5))

(298, 4)

   id account_code                           account_name promo_name
0   1          APW  AANJ Prosperity and Wealth Mdse Corp.        N/A
1   2          ALE              AB Leisure Exponent, Inc.        N/A
2   3          AHC              ACC Hypermart Corporation        N/A
3   4          AWP      Abecure Wellness Products Trading        N/A
4   5          ACT                        Ace Centerpoint        N/A

      id account_code                 account_name promo_name
293  294          XDG  XPH Dry Goods Merchandising        N/A
294  295          YDT             Yca Dale Trading        N/A
295  296          YSI    Yubenco Supermarket, Inc.        N/A
296  297          ZMS   Z.C. Mega Shop-O-Rama Inc.        N/A
297  298          IMP    iMed Pharmacy Corporation        N/A

In [7]:
# Stores / Accounts

# Get dimensions
store_details = pd.read_sql_table(table_name="store_details", con=mis_db, schema="ref")
account_details = pd.read_sql_table(table_name="account_details", con=mis_db, schema="ref")
print(store_details.shape)
store_details = pd.merge(
        store_details,
        account_details[["account_name", "account_chain"]],
        on=["account_name"],
        how="left"
    )
store_details["account_code"] = store_details["bpc_store_code"].str.extract(r"BPC-(\D+)-\d+")
print(store_details.shape)

# Get approved schedules
red_stores = pd.read_excel(f"{mis_file_path}MIS Data\\RED Alert\\RED Bulk Upload.xlsx", sheet_name="Approved Schedule", dtype="str")
red_stores = red_stores[["Account Name", "Store Code", "TOS", "Employee Code"]]
red_stores = red_stores.drop_duplicates(subset=["Account Name", "Store Code", "TOS", "Employee Code"])

store_details = pd.merge(
    store_details,
    red_stores,
    left_on=["account_name", "store_code"],
    right_on=["Account Name", "Store Code"],
    how="left"
)
print(store_details.shape)

store_details = store_details[["bpc_store_code","store_code","account_code","account_chain","store_name","city","province","region","bpc_region", "TOS", "Employee Code"]]

store_details = store_details.rename(columns={
    "account_chain": "account_chain_name",
    "store_name": "account_store_name",
    "TOS": "account_tas",
    "Employee Code": "account_merchandiser"
})



# store_details
store_details.to_csv(r"V:\MIS Data\RED Alert\new_red_sched.csv", index=False, encoding="utf-8")

(13740, 9)
(13740, 11)
(13740, 15)

In [8]:
# Load to database
store_details.to_sql(name="overall_universe_accounts", con=red_db, schema="redreport2026", if_exists="append", index=False, dtype={
    "bpc_store_code": String(255),
    "store_code": String(255),
    "account_code": String(255),
    "account_chain_name": String(255),
    "account_store_name": String(255),
    "city": String(255),
    "province": String(255),
    "region": String(255),
    "bpc_region": String(255),
    "account_tas": String(255),
    "account_merchandiser": String(1000)
})

display(red_stores.shape)
display(red_stores.head(5))
display(red_stores.tail(5))

(5959, 4)

,Account Name,Store Code,TOS,Employee Code
0,Mercury Drug Corporation,0481,"Illustre, Angelita",RIII-MPA-01
2,Watsons Personal Care Store (Phils.) Inc.,1318,"Illustre, Angelita",RIII-MPA-01
4,Robinsons Supermarket Corporation,00213,"Illustre, Angelita",RIII-MPA-01
5,South Star Drug,00737,"Illustre, Angelita",RIII-MPA-01
7,"Pandayan Superstores, Inc.",BTS11,"Illustre, Angelita",RIII-MPA-01

                  Account Name Store Code            TOS Employee Code
7077  Mercury Drug Corporation       0240  Alcala, Allan    NCR-MDE-02
7078  Mercury Drug Corporation       0095  Alcala, Allan    NCR-MDE-02
7079  Mercury Drug Corporation       1022  Alcala, Allan    NCR-MDE-02
7080  Mercury Drug Corporation       1150  Alcala, Allan    NCR-MDE-02
7081  Mercury Drug Corporation       1046  Alcala, Allan    NCR-MDE-02