In [ ]:
# Import Libraries and Modules

import pandas as pd, sqlalchemy as sqla
from sqlalchemy import String, Integer

local_engine = sqla.create_engine("mysql+pymysql://root:1234@localhost:3306")
clone_engine = sqla.create_engine("mysql+mysqlconnector://mis-admin:%40BPCmis2025%40@cloneserver:3306")

In [ ]:
# bulk_upload = pd.read_excel(r"C:\Users\bioco\Downloads\RED Bulk Upload Q3.xlsx")

bulk_upload = pd.read_csv(r"V:\MIS Data\RED Alert\red_sched_7-1-26.csv")
bulk_upload
bulk_upload.to_excel(r"V:\MIS Data\RED Alert\[Python] Red Sched.xlsx", index=False)

In [ ]:
# Push data to local db

bulk_upload.to_sql(
    name="red bulk upload",
    con=local_engine,
    schema="test",
    if_exists="replace",
    index=False,
    chunksize=1000,
    dtype={
        "Employee Code": String(255),
        "Name": String(255),
        "TOS": String(255),
        "Account Name": String(255),
        "Store Name": String(255),
        "Store Code": String(255),
        "Week": Integer(),
        "Day": String(255),
        "City": String(255),
        "Province": String(255),
        "Region": String(255),
        "BPC Region": String(255)
    }
)

# assignment_df.to_sql(
#     name="store_assignment",
#     con=local_engine,
#     schema="ref",
#     if_exists="append",
#     index=False,
#     chunksize=1000,
#     dtype={
#         "year": Integer()
#     },
#     method="multi"
# )

25388

In [21]:
ref_store_details = pd.read_sql("SELECT * FROM ref.store_details", clone_engine)
ref_store_details = ref_store_details[["account_name", "store_code", "bpc_store_code"]]
ref_store_details

                                    account_name store_code bpc_store_code
0          AANJ Prosperity and Wealth Mdse Corp.     AANJ01  BPC-APW-00001
1                      AB Leisure Exponent, Inc.     ABLE01  BPC-ALE-00001
2              Abecure Wellness Products Trading     AWPT01  BPC-AWP-00001
3                      ACC Hypermart Corporation      ACC01  BPC-AHC-00001
4                      ACC Hypermart Corporation      ACC02  BPC-AHC-00002
...                                          ...        ...            ...
13692                   Mercury Drug Corporation       3113  BPC-MDC-01292
13693  Watsons Personal Care Store (Phils.) Inc.       7181  BPC-WPC-01513
13694                   Mercury Drug Corporation       0962  BPC-MDC-01293
13695  Watsons Personal Care Store (Phils.) Inc.       5071  BPC-WPC-01514
13696                        Mindpro Retail Inc.      MRI02  BPC-MRI-00002

[13697 rows x 3 columns]

In [22]:
merged_table = pd.merge(bulk_upload, ref_store_details, left_on=["Account Name", "Store Code"], how="left", right_on=["account_name", "store_code"])
merged_table

,Employee Code,Name,TOS,Account Name,Store Name,Store Code,Week,Day,City,Province,Region,BPC Region,account_name,store_code,bpc_store_code
0,RIII-MPA-01,"Espino, Denn Mark",Angelita Illustre,Mercury Drug Corporation,Mercury Drug Corporation Bulacan Balagtas Town...,0481,1,Monday,Balagtas,Bulacan,Region III,North Luzon,Mercury Drug Corporation,0481,BPC-MDC-00409
1,RIII-MPA-01,"Espino, Denn Mark",Angelita Illustre,Mercury Drug Corporation,Mercury Drug Corporation Bulacan Balagtas Town...,0481,2,Monday,Balagtas,Bulacan,Region III,North Luzon,Mercury Drug Corporation,0481,BPC-MDC-00409
2,RIII-MPA-01,"Espino, Denn Mark",Angelita Illustre,Mercury Drug Corporation,Mercury Drug Corporation Bulacan Balagtas Town...,0481,3,Monday,Balagtas,Bulacan,Region III,North Luzon,Mercury Drug Corporation,0481,BPC-MDC-00409
3,RIII-MPA-01,"Espino, Denn Mark",Angelita Illustre,Mercury Drug Corporation,Mercury Drug Corporation Bulacan Balagtas Town...,0481,4,Monday,Balagtas,Bulacan,Region III,North Luzon,Mercury Drug Corporation,0481,BPC-MDC-00409
4,RIII-MPA-01,"Espino, Denn Mark",Angelita Illustre,Mercury Drug Corporation,Mercury Drug Corporation Bulacan Balagtas Town...,0481,5,Monday,Balagtas,Bulacan,Region III,North Luzon,Mercury Drug Corporation,0481,BPC-MDC-00409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22959,NCR-BA-07,"Galera, Cathyrenz",Tina Madjus,Watsons Personal Care Store (Phils.) Inc.,Watsons Personal Care Store (Phils.) Inc. Sm C...,40,4,Thursday,Quezon City,Metro Manila,NCR,NCR,Watsons Personal Care Store (Phils.) Inc.,40,BPC-WPC-00908
22960,NCR-BA-07,"Galera, Cathyrenz",Tina Madjus,Watsons Personal Care Store (Phils.) Inc.,Watsons Personal Care Store (Phils.) Inc. Nort...,6,1,Saturday,Quezon City,Metro Manila,NCR,NCR,Watsons Personal Care Store (Phils.) Inc.,6,BPC-WPC-01253
22961,NCR-BA-07,"Galera, Cathyrenz",Tina Madjus,Watsons Personal Care Store (Phils.) Inc.,Watsons Personal Care Store (Phils.) Inc. Nort...,6,2,Saturday,Quezon City,Metro Manila,NCR,NCR,Watsons Personal Care Store (Phils.) Inc.,6,BPC-WPC-01253
22962,NCR-BA-07,"Galera, Cathyrenz",Tina Madjus,Watsons Personal Care Store (Phils.) Inc.,Watsons Personal Care Store (Phils.) Inc. Nort...,6,3,Saturday,Quezon City,Metro Manila,NCR,NCR,Watsons Personal Care Store (Phils.) Inc.,6,BPC-WPC-01253
22963,NCR-BA-07,"Galera, Cathyrenz",Tina Madjus,Watsons Personal Care Store (Phils.) Inc.,Watsons Personal Care Store (Phils.) Inc. Nort...,6,4,Saturday,Quezon City,Metro Manila,NCR,NCR,Watsons Personal Care Store (Phils.) Inc.,6,BPC-WPC-01253

In [ ]:
merged_table.to_csv(r"V:\MIS Data\RED Alert\Red Sched with Store details.csv", index=False,encoding="latin-1")