In [15]:
# Import libraries

import pandas as pd, numpy as np, sqlalchemy as sqla
import decouple, shutil, glob
from sqlalchemy import Integer, String, Float, DECIMAL
from IPython.display import display

# root:your_password@localhost/your_database"
# mis-admin:%40BPCmis2025%40@136.158.149.110:3306
# local_engine = sqla.create_engine("mysql+pymysql://mis-admin:%40BPCmis2025%40@136.158.149.110:3306")
local_engine = sqla.create_engine("mysql+pymysql://root:1234@localhost:3306")
engine = sqla.create_engine(decouple.config("MIS_DB"))
dashboard_engine = sqla.create_engine(decouple.config("MIS_DASHBOARD"))
red_engine = sqla.create_engine("mysql+pymysql://mis-red:%40BPCmis2025%40@120.28.99.16:3306")

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [10]:
# Store_Assignment, Merchandiser_Names, Tos_Names Dataframes

assignment_df = pd.read_excel(r"C:\Users\bioco\Downloads\Q3_store_assignment.xlsx")
# diser_df = pd.read_excel(r"C:\Users\bioco\Downloads\Q3_merchandiser_names.xlsx")
tos_df = pd.read_excel(r"C:\Users\bioco\Downloads\Q3_tos_names.xlsx")

print("assignment_df.shape: ", assignment_df.shape)
print("tos_df.shape: ", tos_df.shape)

assignment_df.shape:  (40917, 5)
tos_df.shape:  (40917, 5)

In [11]:
# Export Store_Assignments, Merchandiser_Names, Tos_Names data to Database
# EDIT THE CON PARAMETER FIRSTTTT #

assignment_df.to_sql(
    name="store_assignment",
    con=engine,
    schema="ref",
    if_exists="append",
    index=False,
    chunksize=1000,
    dtype={
        "year": Integer()
    },
    method="multi"
)

tos_df.to_sql(
    name="tos_names",
    con=engine,
    schema="ref",
    if_exists="append",
    index=False,
    chunksize=1000,
    dtype={
        "year": Integer()
    },
    method="multi"
)

# diser_df.to_sql(
#     name="merchandiser_names",
#     con=engine,
#     schema="ref",
#     if_exists="append",
#     index=False,
#     chunksize=1000,
#     dtype={
#         "year": Integer()
#     },
#     method="multi"
# )

40917

In [ ]:
# Target accounts dataframe

# query = 'SELECT * FROM ref.account_details;'

# ref_account_details = pd.read_sql(query, engine)
# ref_account_details = ref_account_details[["order", "bpc_region", "account_name", "account_chain"]]
# ref_account_details.head()

# # Acquire targets from spreadsheet
# target_df = pd.read_excel(r"V:\MIS Data\Universe\Universe (ODBC)-2026.xlsx", sheet_name="unpivot_target", dtype={"account_name": "str", "year": "Int64", "month_name": "str", "target": "float"})
# target_df = target_df.drop(columns="store_code")
# target_df.head()

# # Needed columns
# # order, bpc_region, account_name, account_chain, year, month_name, target

# merged_target_df = pd.merge(target_df, ref_account_details, how="left", on="account_name")
# merged_target_df = merged_target_df[["order", "bpc_region", "account_name", "account_chain", "year", "month_name", "target"]]
# merged_target_df[["order", "year"]] = merged_target_df[["order", "year"]].astype("Int64")

# # df["month_num"] = pd.to_datetime(df["month"], format="%B").dt.month
# merged_target_df["month_num"] = pd.to_datetime(merged_target_df["month_name"], format="%B").dt.month
# merged_target_df = merged_target_df.sort_values(by=["order", "month_num"], ascending=True) 
# merged_target_df = merged_target_df.drop(columns="month_num")
# merged_target_df

# try:
#     merged_target_df.to_sql(
#     name="target_accounts",
#     con=engine,
#     schema="ref",
#     if_exists="append",
#     index=False,
#     chunksize=1000,
#     dtype={
#     "order": Integer(),
#     "year": Integer()
# },
# method="multi"
# )
# except Exception as e:
#     print("Error during upload:", e)

In [ ]:
# Target products dataframe

# target_product_df = pd.read_excel(r"C:\Users\bioco\Downloads\ref_target_products_2026.xlsx", dtype={
#     "order" :"int64", "sales_group": "str",
#     "bpc_region": "str", "account_chain": "str",
#     "product_code": "str",  "product_class": "str", 
#     "target_type": "str", "year":"int64", 
#     "month_name": "str", "target": "float64"
# })

# target_product_df.head()
# target_product_df.tail()

,order,sales_group,bpc_region,account_chain,product_code,product_class,target_type,year,month_name,target
16507,9,S2,NCR,Mercury Drug Corporation,WPS,Skin Care,Baseline,2026,September,78489.835256
16508,9,S2,NCR,Mercury Drug Corporation,WPS,Skin Care,NPI,2026,September,1671.994675
16509,9,S2,NCR,Mercury Drug Corporation,WPS,Skin Care,Promo,2026,September,0.000000
16510,9,S2,NCR,Mercury Drug Corporation,WSCMS,Skin Care,Baseline,2026,September,42720.880458
16511,9,S2,NCR,Mercury Drug Corporation,WSCMS,Skin Care,NPI,2026,September,655.421956

In [ ]:
# target_product_df.to_sql(
#     name="target_products",
#     con=engine,
#     schema="ref",
#     if_exists="append",
#     index=False,
#     chunksize=1000,
#     dtype={
#         "year": Integer()
#     },
#     method="multi"
# )

16512

In [18]:
# TEMPORARY TARGETS TABLE 

s4_targets = pd.read_excel(r"C:\Users\bioco\Downloads\ref_target_products_2026_1.xlsx", sheet_name="s4_targets_no_target_type")

s4_targets = s4_targets[s4_targets["target"] != 0]

display(s4_targets.head())
s4_targets.shape

,sales_group,bpc_region,account_chain,product_code,product_class,year,month_name,target
48,S4,North Luzon,"Big A Department Store, Inc.",BACS,Skin Care,2026,January,728
49,S4,North Luzon,"Big A Department Store, Inc.",BACS,Skin Care,2026,February,515
50,S4,North Luzon,"Big A Department Store, Inc.",BACS,Skin Care,2026,March,425
51,S4,North Luzon,"Big A Department Store, Inc.",BACS,Skin Care,2026,April,370
52,S4,North Luzon,"Big A Department Store, Inc.",BACS,Skin Care,2026,May,671

(28955, 8)

In [19]:
# Export data to local dashboard-sales database

s4_targets.to_sql(
    name="s4_targets",
    con=local_engine,
    schema="dashboard-sales",
    if_exists="append",
    index=False,
    chunksize=10000,
    method="multi"
)

28955

In [16]:
# 'dashboard-sales'.employees table

employees_dashboard_sales = pd.read_excel(r"C:\eli_dump\to_dashboard_employees.xlsx")
employees_dashboard_sales.head()

                employee_name plantilla_code department position
0  Santillan, Ma. Cristina M.     NCR-TOS-01      Sales      TOS
1             Acala, Allan A.     NCR-TOS-02      Sales      TOS
2                      Vacant     NCR-TOS-03      Sales      TOS
3                      Vacant     NCR-TOS-04      Sales      TOS
4                      Vacant     CAR-TOS-01      Sales      TOS

In [ ]:
employees_dashboard_sales.to_sql(
    name="employees",
    schema="dashboard-sales",
    # con=,
    if_exists="append",
    index=False,
    chunksize=1000,
    method="multi"
)

155